kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-external-snapshotter-operator-leaderelection
  namespace: openshift-storage
subjects:
  - kind: ServiceAccount
    name: odf-external-snapshotter-operator
    namespace: openshift-storage
roleRef:
  kind: Role
  name: odf-external-snapshotter-operator-leaderelection
  apiGroup: rbac.authorization.k8s.io
