kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-external-snapshotter-operator-role
subjects:
  - kind: ServiceAccount
    name: odf-external-snapshotter-operator
    namespace: openshift-storage
roleRef:
  kind: ClusterRole
  name: odf-external-snapshotter-operator-runner
  apiGroup: rbac.authorization.k8s.io
